-- 1. CREACIÓN DE TABLAS:

CREATE TABLE empleados (
	id SERIAL PRIMARY KEY, 
	nombre VARCHAR(100) NOT NULL,
	correo VARCHAR(100), 
	departamento_id INTEGER,
	FOREIGN KEY (departamento_id) REFERENCES departamentos(id)
);

-- QUE ES UNA CLAVE PRIMARIA Y POR QUÉ SE USA EN ID?

-- R. ES EL CAMPO UNICO E IRREPETIBLE DE UNA TABLA QUE SIRVE PARA IDENTIFICAR UN REGISTRO ESPECIFICO DE FORMA EXACTA.
--  EL ID SE USA PARA ASEGURAR QUE NO EXISTAN DOS FILAS IGUALES Y PERMITIR QUE OTRAS TABLAS PUEDAN REFERENCIAS REGISTROS ESPECIFICOS.

-- QUE SIGNIFICA NOT NULL?

-- R. ES UNA RESTRICCIÓN QUE SIGNIFICA "NO NULO" O "NO VACIO",INDICA DE FORMA OBLIGATORIA QUE ESA COLUMNA NUNCA PUEDE GUARDARSE SIN UN VALOR.

-- QUE RELACIÓN EXISTE ENTRE EMPLEADOS Y DEPARTAMENTOS?

--R. UNO A MUCHOS, UN DEPARTAMENTO PUEDE TENER MUCHOS EMPLEADOS PERO CADA EMPLEADO PERTENECE A UN DEPARTAMENTO.


-- 2. MODIFICAR TABLAS EXISTENTES:

ALTER TABLE empleados ADD COLUMN fecha_ingreso DATE;
ALTER TABLE departamentos ADD COLUMN ubicacion VARCHAR(100);

ALTER TABLE empleados ALTER COLUMN correo SET NOT NULL;

-- SI SE INTENTA MODIFICAR EL VALOR DE UNA CLAVE PRIMARIA QUE YA ESTÁ SIENDO REFERENCIADA, DARÁ ERROR Y NO PERMITIRÁ EL CAMBIO HASTA QUE SE ELIMINEN LAS RESTRICCIONES.


-- 3. ELIMINAR Y TRUNCAR TABLAS:

DROP TABLE IF EXISTS empleados;

CREATE TEMP TABLE prueba_temporal (
    id SERIAL PRIMARY KEY,
    descripcion TEXT
);

INSERT INTO prueba_temporal (descripcion) VALUES ('Dato A'), ('Dato B');

TRUNCATE TABLE prueba_temporal;

-- DIFERENCIA ENTRE DELETE Y TRUNCATE:

-- R. LA DIFRENCIA ES QUE DELETE  BORRA FILAS DE UNA EN UNA DE MANERA SELECTIVA Y TRUNCATE VACÍA LA TABLA POR COMPLETO, RESTABLECIENDO LA ESTRUCTURA AL ESTADO INCIAL.
